@startuml
'https://plantuml.com/activity-diagram-beta

start
:Administrateur ouvre l'application d'administration;
if (Administrateur est connecté ?) then (oui)
else (non)
repeat :Affichage du formulaire de connexion;
:Administrateur entre son identifiant et son mot de passe;
:Administrateur clique sur valider;
backward:Affichage des erreurs;
repeat while (Informations valides ?) is (non) not (oui)
:Connexion au compte;
endif
:Affichage de la page d'accueil;
stop

@enduml
