@startuml
'https://plantuml.com/activity-diagram-beta

start
:Baptiste arrive sur le site;
:Baptiste clique sur "Se connecter";
:Affichage du formulaire de connexion;
:Baptiste entre son identifiant et son mot de passe;
:Baptiste clique sur valider;
:Connexion au compte;
:Redirection vers la dernière page visitée;
:Baptiste clique sur "Mon compte";
:Baptiste clique sur "Mes commandes";
:Affichage de la page d'historique de commandes;
stop

@enduml
