@startuml
'https://plantuml.com/activity-diagram-beta

start
:Baptiste arrive sur le site;
:Baptiste clique sur "Se connecter";
:Affichage du formulaire de connexion;
:Baptiste clique sur "Mot de passe oublié";
repeat :Affichage du formulaire d'oubli de mot de passe';
:Baptiste entre son adresse mail;
backward:Affichage de l'erreur associé;
repeat while (Un compte est associé à cette\n adresse et l'adresse a été vérifiée) is (non) not (oui)
:Envoi d'un mail à l'adresse indiquée;
:Baptiste clique sur le lien du mail;
repeat :Affichage du formulaire de réinitialisation de mot de passe;
:Baptiste entre son nouveau mot de passe;
:Baptiste confirme son nouveau mot de passe;
backward:Affichage de l'erreur associé;
repeat while (Les deux mot de passe sont identiques et il est suffisamment fort) is (non) not (oui)
:Sauvegarde du nouveau mot de passe;
:Envoi d'un mail pour indiquer le changement;
:Affichage d'un message de succès;
stop

@enduml
