@startuml
'https://plantuml.com/activity-diagram-beta

title Processus complet de prise de commande

start

:Baptiste arrive sur le site;
:Baptiste clique sur "Se connecter";
:Affichage du formulaire de connexion;
:Baptiste entre son identifiant et son mot de passe;
:Baptiste clique sur valider;
:Connexion au compte;
:Redirection vers la dernière page visitée;
:Baptiste clique sur "Menu";
:Affichage de la page "Menu";

repeat :Baptiste clique sur le produit qu'il souhaite;
    :Baptiste entre la quantité;
    :Baptiste clique sur "Valider";
    :Ajout du produit au panier;
repeat while (Baptiste souhaite commander un autre produit) is (oui) not (non)

:Baptiste clique sur "Valider ma commande";
:Enregistrement de la commande;
:Actualisation de la liste des commandes sur l'application back-office;
:Affichage d'une page proposant le paiement en ligne immédiat;

if (Baptiste souhaite-il payer en ligne ?) then (Oui)
    :Baptiste clique sur le bouton "Payer maintenant";

    repeat :Affichage du formulaire de paiement;
        :Baptiste sélectionne son mode de paiement;
        :Baptiste entre ses informations de paiement;
        :Envoi d'une requête à la plateforme de paiement;
        backward:Affichage d'un message d'erreur;
    repeat while (Le paiement est-il effectué ?) is (non) not (oui)

    :Affichage d'un message de succès;
    :Passage de l'état de paiement en "Oui";
else (Non)
    :Baptiste clique sur le bouton "Payer à la réception";
endif

fork
  :Cuisinier clique sur l'onglet "Commandes";
  :Affichage de la liste des commandes en attente;
  :Cuisinier clique sur une commande dans la liste;
  :Affichage de la page d'informations de la commande;
  :Cuisinier clique sur le bouton "Commande en préparation";
  :Changement de l'état de la commande pour "En préparation";
  :Affichage de la page "Rappel de recette";
  :Cuisinier clique sur le bouton "Commande prête";
  :Changement de l'état de la commande pour "Prête";
fork again
  :Livreur clique sur le bouton "Prêt à livrer";
  :Ajout du livreur à la liste d'attente;
  :Assignation du Livreur à la commande;
  :Affichage de la position du livreur à Baptiste (sur page de suivi);
  :Envoi d'une notification au livreur;
end fork

:Livreur clique sur l'onglet "Ma Livraison";
:Affichage de la page d'informations de la commande;
:Livreur arive à moins de 500m du point de livraison;
:Envoi d'une notification à Baptiste;
:Livreur clique sur l'onglet "Ma Livraison";
:Affichage de la page d'informations de la commande;
:Livreur clique sur le bouton "Commande livrée";
:Changement de l'état de la commande pour "Livrée";
:Archivage de la commande dans l'historique des commandes;
:Suppression de la commande;

stop

@enduml
