@startuml
'https://plantuml.com/activity-diagram-beta

start
:Livreur ouvre l'application employé;
if (Livreur est connecté ?) then (oui)
else (non)
repeat :Affichage du formulaire de connexion;
:Livreur entre son identifiant et son mot de passe;
:Livreur clique sur valider;
backward:Affichage des erreurs;
repeat while (Informations valides ?) is (non) not (oui)
:Connexion au compte;
endif
:Affichage de la page d'accueil;
:Livreur clique sur l'icône du menu déroulant;
:Livreur clique sur l'onglet "Commandes";
repeat :Affichage de la page "Commandes";
:Livreur clique sur une commande dans la liste;
:Affichage de la page d'informations de la commande;
:Livreur clique sur le bouton "Réserver";
backward:Affichage d'un popup d'erreur;
repeat while (La commande est-elle déjà réservée ?) is (oui) not (non)
:Assignation du livreur comme en charge de la commande;
if (La commande est-elle déjà prête ?) then (non)
else (oui)
:Affichage d'un message popup indiquant que la commande est prête à être livrée;
endif
:Suppression de la commande de la liste des commandes non assignées;
:Affichage de la page d'informations de la commande;
stop

@enduml
